/*
 * Raptor Runner — Electron main process.
 *
 * In dev mode: loads the Vite dev server at localhost:5173.
 * In production: loads the built dist/index.html via file://.
 *
 * The service worker is silently ignored in Electron (file:// doesn't
 * support SW registration). The VitePWA plugin's "auto" inject
 * handles this gracefully — the register call fails silently and the
 * game runs without offline support, which is fine for a desktop app.
 *
 * Steam integration:
 *   steamworks.js is initialized once before window creation. If Steam
 *   isn't running / the user isn't logged in / the SDK fails to load,
 *   steamClient stays null and every bridge call short-circuits — the
 *   game still runs and unlocks land in localStorage.
 *   STEAM_APP_ID defaults to 480 (Spacewar) for dev; override via env.
 */

import { app, BrowserWindow, ipcMain, shell } from "electron";
import path from "path";
import fs from "fs";
import steamworks from "steamworks.js";

const isDev = process.env.NODE_ENV === "development" || !app.isPackaged;

// Override the product name BEFORE any window is created so dev-mode
// dock tooltips ("Electron"), the About menu, and userData paths all
// read "Raptor Runner". Packaged builds pick this up from the Info.plist
// generated by electron-builder's `productName`, so this line is a
// no-op in production.
app.setName("Raptor Runner");

const STEAM_APP_ID = Number(process.env.STEAM_APP_ID ?? 480);

type SteamClient = ReturnType<typeof steamworks.init>;
let steamClient: SteamClient | null = null;

try {
  steamClient = steamworks.init(STEAM_APP_ID);
  steamworks.electronEnableSteamOverlay();
  console.log(`[steam] init ok, appid ${STEAM_APP_ID}`);
} catch (err) {
  console.warn("[steam] init failed, running without Steam:", err);
  steamClient = null;
}

// IPC: renderer asks whether Steam is usable this session.
ipcMain.handle("steam:isAvailable", () => steamClient !== null);

// IPC: quit the app. Called from the desktop-only Quit button in
// the settings menu.
//
// Force-close every window before calling app.quit(). On macOS
// app.quit() alone sometimes gets deferred by the platform (any
// open transition / animation / "should close?" check can hold it),
// and the player sees a button that does nothing. win.destroy()
// skips the usual close-event path so there's no prevention hook
// the renderer could have silently installed. After the windows
// are gone, window-all-closed handles Linux/Windows and app.quit()
// finishes macOS.
ipcMain.handle("app:quit", () => {
  for (const w of BrowserWindow.getAllWindows()) {
    try {
      w.destroy();
    } catch {
      /* already destroyed — ignore */
    }
  }
  app.quit();
});

// Steam overlay dialogs (Friends, Achievements, etc.). Activates the
// in-game Steam overlay to a specific panel. Returns false if Steam
// isn't available or the client refuses — lets the renderer gracefully
// fall back.
//
// Note: the Steam overlay has known rendering limitations on macOS.
// Valve's macOS overlay support for non-native apps (including
// Electron) is unreliable — the overlay may not appear, or may appear
// without proper interaction. Windows and Linux are unaffected. The
// IPC still fires; if the overlay doesn't pop, it's a Valve/OS issue,
// not ours.
type OverlayDialog =
  | "Friends"
  | "Community"
  | "Players"
  | "Settings"
  | "OfficialGameGroup"
  | "Stats"
  | "Achievements";
const OVERLAY_DIALOG_MAP: Record<OverlayDialog, number> = {
  Friends: 0,
  Community: 1,
  Players: 2,
  Settings: 3,
  OfficialGameGroup: 4,
  Stats: 5,
  Achievements: 6,
};
ipcMain.handle("steam:openOverlay", (_evt, dialog: OverlayDialog) => {
  if (!steamClient) return false;
  const code = OVERLAY_DIALOG_MAP[dialog];
  if (code == null) return false;
  try {
    steamClient.overlay.activateDialog(code);
    return true;
  } catch (err) {
    console.warn("[steam] openOverlay failed:", dialog, err);
    return false;
  }
});

// Open the Steam overlay to a specific URL (store page, news, etc.).
ipcMain.handle("steam:openOverlayUrl", (_evt, url: string) => {
  if (!steamClient) return false;
  try {
    steamClient.overlay.activateToWebPage(url);
    return true;
  } catch (err) {
    console.warn("[steam] openOverlayUrl failed:", url, err);
    return false;
  }
});

/**
 * Persisted user prefs (currently just fullscreen mode). Stored as a
 * tiny JSON blob in app.getPath("userData") so the choice survives
 * app restarts without reaching into localStorage.
 *
 * Kept intentionally minimal: reads are synchronous at app start so
 * we can apply prefs to the BrowserWindow constructor, writes are
 * best-effort from the IPC handler and never block the caller.
 */
type Prefs = { fullscreen?: boolean };
let _prefsPath = "";
function prefsPath(): string {
  if (!_prefsPath) {
    _prefsPath = path.join(app.getPath("userData"), "prefs.json");
  }
  return _prefsPath;
}
function loadPrefs(): Prefs {
  try {
    return JSON.parse(fs.readFileSync(prefsPath(), "utf8")) as Prefs;
  } catch {
    return {};
  }
}
function savePrefs(patch: Prefs): void {
  try {
    const current = loadPrefs();
    const next = { ...current, ...patch };
    fs.writeFileSync(prefsPath(), JSON.stringify(next), "utf8");
  } catch (err) {
    console.warn("[prefs] save failed:", err);
  }
}

// IPC: toggle fullscreen from the desktop menu. Persists so the
// preference survives app restart.
ipcMain.handle(
  "window:setFullscreen",
  (evt, wantFullscreen: boolean) => {
    const win = BrowserWindow.fromWebContents(evt.sender);
    if (!win || win.isDestroyed()) return false;
    const isMac = process.platform === "darwin";
    if (isMac) {
      win.setSimpleFullScreen(!!wantFullscreen);
    } else {
      win.setFullScreen(!!wantFullscreen);
    }
    savePrefs({ fullscreen: !!wantFullscreen });
    return !!wantFullscreen;
  },
);

// IPC: read current fullscreen state (used by the menu to sync the
// toggle label when the overlay opens).
ipcMain.handle("window:isFullscreen", (evt) => {
  const win = BrowserWindow.fromWebContents(evt.sender);
  if (!win || win.isDestroyed()) return false;
  return process.platform === "darwin"
    ? win.isSimpleFullScreen()
    : win.isFullScreen();
});

// IPC: activate a Steam achievement by its API Name. Idempotent on
// Steam's side — re-activating an already-unlocked achievement is a
// no-op, so we don't need to gate on isActivated first. Returns true
// on success, false on any failure (SDK absent, name unknown, etc).
ipcMain.handle("steam:activateAchievement", (_evt, apiName: string) => {
  if (!steamClient) return false;
  try {
    return steamClient.achievement.activate(apiName);
  } catch (err) {
    console.warn("[steam] activateAchievement failed:", apiName, err);
    return false;
  }
});

// IPC: batched state fetch used by the init reconcile pass. Returns
// a record of { apiName: unlocked } for every name the renderer asks
// about. Returns an empty object when Steam isn't available so the
// renderer doesn't need a special null code path.
ipcMain.handle(
  "steam:getAchievementStates",
  (_evt, apiNames: string[]): Record<string, boolean> => {
    const out: Record<string, boolean> = {};
    if (!steamClient) return out;
    for (const name of apiNames) {
      try {
        out[name] = steamClient.achievement.isActivated(name);
      } catch {
        out[name] = false;
      }
    }
    return out;
  },
);

function createWindow(): void {
  const isMac = process.platform === "darwin";
  // Default fullscreen for desktop games. Player can opt-out via the
  // Fullscreen toggle in the settings menu; that writes prefs.json,
  // which we read here to restore the preference on next launch.
  const prefs = loadPrefs();
  const wantFullscreen = prefs.fullscreen !== false; // default true

  const win = new BrowserWindow({
    width: 1280,
    height: 800,
    minWidth: 800,
    minHeight: 500,
    title: "Raptor Runner",
    icon: path.join(__dirname, "../public/assets/icon-rounded-1024.png"),
    webPreferences: {
      preload: path.join(__dirname, "preload.js"),
      contextIsolation: true,
      nodeIntegration: false,
    },
    // Fullscreen + simpleFullScreen together are required on macOS:
    //   - `fullscreen: true` alone uses Lion-style Spaces transition
    //     which animates the window visibly even with show: false
    //     (caused the earlier FOUC-behind-splash bug).
    //   - `simpleFullscreen: true` alone just ENABLES the capability;
    //     the window still opens windowed unless fullscreen is set.
    //   - Both together: window opens instantly at screen size in
    //     pre-Lion style fullscreen, no Spaces animation.
    // On Windows/Linux plain fullscreen is already animation-free.
    fullscreen: wantFullscreen,
    simpleFullscreen: isMac,
    titleBarStyle: isMac ? "hiddenInset" : "default",
    backgroundColor: "#50b4cd", // sky-blue matches splash + game sky
    show: false, // wait for first paint so the splash is what appears
  });

  // Show the window only after the renderer has painted at least
  // once. With the inline splash in index.html, that first paint is
  // already the splash — so the window becomes visible already
  // showing the splash, no black/white flash.
  win.once("ready-to-show", () => {
    if (!win.isDestroyed()) win.show();
  });

  // Open external links (GitHub, portfolio, ricos.site, etc.) in the
  // user's system browser instead of inside the Electron window.
  // Without this, an <a target="_blank"> would either load inside
  // the main window (breaking the game) or open a bare Electron
  // window with no chrome. shell.openExternal hands the URL to the
  // OS so it opens in Safari/Chrome/Firefox/whatever.
  const handleExternal = (url: string) => {
    if (/^https?:\/\//i.test(url)) {
      shell.openExternal(url).catch(() => {
        /* swallow — best-effort */
      });
      return { action: "deny" as const };
    }
    return { action: "allow" as const };
  };
  win.webContents.setWindowOpenHandler(({ url }) => handleExternal(url));
  // Same handler for iframe contents (about.html, imprint.html):
  win.webContents.on("did-attach-webview", (_e, wc) => {
    wc.setWindowOpenHandler(({ url }) => handleExternal(url));
  });
  // Also intercept top-level navigations — clicking a link without
  // target="_blank" would otherwise replace the renderer with the
  // external URL and break the game.
  win.webContents.on("will-navigate", (event, url) => {
    const current = win.webContents.getURL();
    // Let same-origin navigation continue (e.g. Vite dev HMR,
    // in-app hash changes). Block cross-origin http(s) loads in
    // the main webContents.
    if (/^https?:\/\//i.test(url)) {
      try {
        const target = new URL(url);
        const here = new URL(current);
        if (target.origin !== here.origin) {
          event.preventDefault();
          shell.openExternal(url).catch(() => {});
        }
      } catch {
        /* malformed URL — let Electron handle */
      }
    }
  });

  if (isDev) {
    // Dev: connect to the Vite dev server for HMR.
    const DEV_URL = "http://localhost:5173";
    win.loadURL(DEV_URL);
    // Open DevTools in dev mode (detached so it doesn't resize the game)
    win.webContents.openDevTools({ mode: "detach" });

    // Recover from transient dev-server outages. When Vite decides to
    // restart its own server (e.g. because a file reachable from
    // vite.config.ts's dep graph changed), there's a ~200–500ms
    // window where the port is closed. If the Electron window tries
    // to reload during that window, Chromium drops the page onto the
    // ERR_CONNECTION_RESET / ERR_CONNECTION_REFUSED error screen and
    // never retries on its own — the window is stuck on the sad-face
    // page until you kill Electron and rerun `npm run dev:desktop`.
    //
    // Fix: listen for did-fail-load, and if the failure is (a) on
    // the main frame, (b) against the Vite dev URL, and (c) a
    // recoverable network error code, schedule a retry loop. Each
    // retry is a fresh loadURL; once the server is back up the page
    // loads and HMR is live again.
    //
    // Chromium network error codes:
    //   -3   ABORTED            (we started a new nav; ignore)
    //   -7   TIMED_OUT
    //  -21   NETWORK_CHANGED
    // -101   CONNECTION_RESET   ← the one we see
    // -102   CONNECTION_REFUSED ← common when Vite is still spinning up
    // -104   CONNECTION_FAILED
    // -105   NAME_NOT_RESOLVED
    // -106   INTERNET_DISCONNECTED
    const RECOVERABLE_ERRORS = new Set([-7, -21, -101, -102, -104, -105, -106]);
    let retrying = false;
    win.webContents.on(
      "did-fail-load",
      (_evt, errorCode, errorDescription, validatedURL, isMainFrame) => {
        if (!isMainFrame) return;
        if (!validatedURL.startsWith(DEV_URL)) return;
        if (!RECOVERABLE_ERRORS.has(errorCode)) return;
        if (retrying) return;
        retrying = true;
        console.log(
          `[dev-reload] ${errorDescription} (${errorCode}); retrying`,
        );
        const tryReload = () => {
          if (win.isDestroyed()) {
            retrying = false;
            return;
          }
          win.loadURL(DEV_URL).catch(() => {
            // still failing — keep polling until the server is back.
            // 500 ms is small enough that the blue screen is barely
            // visible, big enough that we're not hammering the port.
            setTimeout(tryReload, 500);
          });
        };
        // Small initial delay so Vite has a moment to rebind.
        setTimeout(tryReload, 300);
      },
    );
    // Once a reload succeeds we can accept another recovery attempt.
    win.webContents.on("did-finish-load", () => {
      retrying = false;
    });
  } else {
    // Production: load the built dist/index.html
    win.loadFile(path.join(__dirname, "../dist/index.html"));
  }

  // Force landscape by preventing the window from being narrower than tall
  win.on("resize", () => {
    const [w, h] = win.getSize();
    if (h > w) {
      win.setSize(h, w); // swap dimensions to force landscape
    }
  });
}

app.whenReady().then(() => {
  // macOS dock icon. In packaged builds this comes from the .icns
  // baked into the app bundle (build.mac.icon), but in dev mode
  // Electron shows its own icon unless we override it here. Windows
  // / Linux dock/taskbar icons come from the BrowserWindow `icon:`
  // option below.
  if (process.platform === "darwin" && app.dock) {
    try {
      app.dock.setIcon(
        path.join(__dirname, "..", "public", "assets", "icon-512.png"),
      );
    } catch (err) {
      console.warn("[app] failed to set dock icon:", err);
    }
  }

  createWindow();

  // macOS: re-create window when dock icon is clicked and no windows open
  app.on("activate", () => {
    if (BrowserWindow.getAllWindows().length === 0) {
      createWindow();
    }
  });
});

// Quit when all windows are closed (except on macOS where apps stay
// running until explicitly quit via Cmd+Q).
app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});
