#!/usr/bin/env python3
"""Extract 22 per-frame silhouette polygons from the pterodactyl
sprite sheet. For each 5×5 cell with content, sample N evenly-spaced
columns across the non-transparent bounding box; for each column
record the top-most and bottom-most opaque pixel as two polygon
vertices. The resulting 2N-vertex outline is a close-fitting envelope
of the full body + wings silhouette, rendered as a single polygon
(top edge left→right, then bottom edge right→left).

Output: TypeScript literal for src/entities/pterodactyl.ts. Copy-paste
the generated block over the existing PTERODACTYL_COLLISION array.
"""

from PIL import Image
from pathlib import Path

SHEET = Path(__file__).parent.parent / "public" / "assets" / "pterodactyl-sprite.png"
COLS, ROWS = 5, 5
FRAMES = 22  # 5×4 + 2 in last row
COLUMNS_PER_FRAME = 14  # sampling resolution along x
ALPHA_THRESHOLD = 32


def load_frame_alpha(sheet, col, row):
    w, h = sheet.size
    fw, fh = w // COLS, h // ROWS
    box = (col * fw, row * fh, (col + 1) * fw, (row + 1) * fh)
    frame = sheet.crop(box)
    # Both source spritesheets we've seen are black-background PNGs
    # (no alpha channel). Convert to RGBA and key out the black so we
    # can treat "opaque" as "non-black pixel".
    if frame.mode != "RGBA":
        frame = frame.convert("RGBA")
    pixels = frame.load()
    mask = [[False] * fh for _ in range(fw)]
    for y in range(fh):
        for x in range(fw):
            r, g, b, a = pixels[x, y]
            if a < ALPHA_THRESHOLD:
                continue
            if r + g + b < 24:  # ~pure black bg
                continue
            mask[x][y] = True
    return mask, fw, fh


def frame_bbox(mask, fw, fh):
    xs_with_content = []
    minY = fh
    maxY = -1
    for x in range(fw):
        column_has = False
        for y in range(fh):
            if mask[x][y]:
                column_has = True
                if y < minY:
                    minY = y
                if y > maxY:
                    maxY = y
        if column_has:
            xs_with_content.append(x)
    if not xs_with_content:
        return None
    return min(xs_with_content), minY, max(xs_with_content), maxY


def extract_polygon(mask, fw, fh):
    bbox = frame_bbox(mask, fw, fh)
    if bbox is None:
        return None
    x0, y0, x1, y1 = bbox
    # Sample COLUMNS_PER_FRAME x-positions evenly across the bbox.
    cols = []
    for i in range(COLUMNS_PER_FRAME):
        t = i / (COLUMNS_PER_FRAME - 1) if COLUMNS_PER_FRAME > 1 else 0.5
        x = int(round(x0 + t * (x1 - x0)))
        # Walk top→bottom and bottom→top to find the silhouette edges.
        top = None
        bot = None
        for y in range(fh):
            if mask[x][y]:
                top = y
                break
        for y in range(fh - 1, -1, -1):
            if mask[x][y]:
                bot = y
                break
        if top is None or bot is None:
            continue
        cols.append((x, top, bot))
    if len(cols) < 3:
        return None
    # Build a single polygon: top edge left→right, then bottom edge
    # right→left. Normalize to [0, 1] relative to the full frame.
    top_pts = [(x / fw, top / fh) for (x, top, _) in cols]
    bot_pts = [(x / fw, bot / fh) for (x, _, bot) in cols]
    poly = top_pts + list(reversed(bot_pts))
    return poly


def main():
    sheet = Image.open(SHEET)
    print("// Auto-generated by scripts/extract-ptero-polygons.py —")
    print("// re-run after swapping the sprite sheet. Each polygon is the")
    print("// silhouette (body + wings) sampled column-by-column, so the")
    print("// wing extents are frame-accurate and a clipped wing-tip now")
    print("// counts as a hit.")
    print("export const PTERODACTYL_COLLISION: ReadonlyArray<ReadonlyArray<NormalizedPoint>> = [")
    frame_idx = 0
    for row in range(ROWS):
        for col in range(COLS):
            if frame_idx >= FRAMES:
                break
            mask, fw, fh = load_frame_alpha(sheet, col, row)
            poly = extract_polygon(mask, fw, fh)
            if poly is None:
                print(f"  [], // frame {frame_idx} (empty)")
            else:
                pts = ", ".join(
                    f"[{x:.4f}, {y:.4f}]" for (x, y) in poly
                )
                print(f"  [{pts}], // frame {frame_idx}")
            frame_idx += 1
    print("];")


if __name__ == "__main__":
    main()
